// Generated by CIRCT firtool-1.62.0
module Decode24a(	// src/main/scala/exp2/Decode24.scala:6:7
  input        clock,	// src/main/scala/exp2/Decode24.scala:6:7
               reset,	// src/main/scala/exp2/Decode24.scala:6:7
  input  [1:0] io_x,	// src/main/scala/exp2/Decode24.scala:7:16
  input        io_en,	// src/main/scala/exp2/Decode24.scala:7:16
  output [3:0] io_y	// src/main/scala/exp2/Decode24.scala:7:16
);

  wire [3:0][3:0] _GEN = {{{&io_x, 3'h0}}, {4'h4}, {4'h2}, {4'h1}};	// src/main/scala/exp2/Decode24.scala:13:24, :16:22, :18:19, :21:19, :24:19, :27:19
  assign io_y = io_en ? _GEN[io_x] : 4'h0;	// src/main/scala/exp2/Decode24.scala:6:7, :13:24, :15:17, :16:22, :18:19, :21:19, :24:19, :31:11
endmodule

