// Generated by CIRCT firtool-1.62.0
module Decode24b(	// src/main/scala/exp2/Decode24.scala:41:7
  input        clock,	// src/main/scala/exp2/Decode24.scala:41:7
               reset,	// src/main/scala/exp2/Decode24.scala:41:7
  input  [1:0] io_x,	// src/main/scala/exp2/Decode24.scala:42:16
  input        io_en,	// src/main/scala/exp2/Decode24.scala:42:16
  output [3:0] io_y	// src/main/scala/exp2/Decode24.scala:42:16
);

  assign io_y = io_en ? 4'h1 << io_x : 4'h0;	// src/main/scala/exp2/Decode24.scala:41:7, :50:17, :51:{11,18}, :53:11
endmodule

