// Generated by CIRCT firtool-1.62.0
module Encode42p(	// src/main/scala/exp2/Encode42p.scala:6:7
  input        clock,	// src/main/scala/exp2/Encode42p.scala:6:7
               reset,	// src/main/scala/exp2/Encode42p.scala:6:7
  input  [3:0] io_x,	// src/main/scala/exp2/Encode42p.scala:7:16
  input        io_en,	// src/main/scala/exp2/Encode42p.scala:7:16
  output [1:0] io_y	// src/main/scala/exp2/Encode42p.scala:7:16
);

  assign io_y = io_en ? (io_x[3] ? 2'h3 : io_x[2] ? 2'h2 : {1'h0, io_x[1]}) : 2'h0;	// src/main/scala/exp2/Encode42p.scala:6:7, :13:24, :15:17, :17:{22,27}, :18:19, :22:11
endmodule

