// Generated by CIRCT firtool-1.62.0
module Alu(	// src/main/scala/exp3/Alu.scala:6:7
  input        clock,	// src/main/scala/exp3/Alu.scala:6:7
               reset,	// src/main/scala/exp3/Alu.scala:6:7
  input  [3:0] io_a,	// src/main/scala/exp3/Alu.scala:7:16
               io_b,	// src/main/scala/exp3/Alu.scala:7:16
  input  [2:0] io_op,	// src/main/scala/exp3/Alu.scala:7:16
  output [3:0] io_res	// src/main/scala/exp3/Alu.scala:7:16
);

  wire [3:0]      _GEN =
    {3'h0, io_op == 3'h6 ? $signed(io_a) < $signed(io_b) : (&io_op) & io_a == io_b};	// src/main/scala/exp3/Alu.scala:14:26, :16:19, :36:{23,31}, :43:{23,33}, :44:21, :46:21
  wire [7:0][3:0] _GEN_0 =
    {{_GEN},
     {_GEN},
     {io_a ^ io_b},
     {io_a | io_b},
     {io_a & io_b},
     {~io_a},
     {io_a - io_b},
     {io_a + io_b}};	// src/main/scala/exp3/Alu.scala:16:19, :18:{17,25}, :21:{17,25}, :24:{17,20}, :27:{17,25}, :30:{17,25}, :33:{17,25}, :36:31
  assign io_res = _GEN_0[io_op];	// src/main/scala/exp3/Alu.scala:6:7, :16:19, :18:17, :21:17, :24:17, :27:17, :30:17, :33:17
endmodule

