// Generated by CIRCT firtool-1.62.0
module Encode42(	// src/main/scala/exp2/Encode42.scala:6:7
  input        clock,	// src/main/scala/exp2/Encode42.scala:6:7
               reset,	// src/main/scala/exp2/Encode42.scala:6:7
  input  [3:0] io_x,	// src/main/scala/exp2/Encode42.scala:7:16
  input        io_en,	// src/main/scala/exp2/Encode42.scala:7:16
  output [1:0] io_y	// src/main/scala/exp2/Encode42.scala:7:16
);

  assign io_y =
    ~io_en | io_x == 4'h1
      ? 2'h0
      : io_x == 4'h2 ? 2'h1 : io_x == 4'h4 ? 2'h2 : {2{io_x == 4'h8}};	// src/main/scala/exp2/Encode42.scala:6:7, :13:24, :15:17, :16:22, :21:19, :24:19, :27:19, :31:11
endmodule

