// Generated by CIRCT firtool-1.62.0
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

module PS2Keyboard(	// src/main/scala/exp7/PS2Keyboard.scala:6:7
  input        clock,	// src/main/scala/exp7/PS2Keyboard.scala:6:7
               reset,	// src/main/scala/exp7/PS2Keyboard.scala:6:7
               io_ps2_clk,	// src/main/scala/exp7/PS2Keyboard.scala:7:16
               io_ps2_data,	// src/main/scala/exp7/PS2Keyboard.scala:7:16
               io_out_ready,	// src/main/scala/exp7/PS2Keyboard.scala:7:16
  output       io_out_valid,	// src/main/scala/exp7/PS2Keyboard.scala:7:16
  output [7:0] io_out_bits	// src/main/scala/exp7/PS2Keyboard.scala:7:16
);

  reg [2:0] ps2_clk_sync;	// src/main/scala/exp7/PS2Keyboard.scala:13:26
  reg       buffer_0;	// src/main/scala/exp7/PS2Keyboard.scala:14:21
  reg       buffer_1;	// src/main/scala/exp7/PS2Keyboard.scala:14:21
  reg       buffer_2;	// src/main/scala/exp7/PS2Keyboard.scala:14:21
  reg       buffer_3;	// src/main/scala/exp7/PS2Keyboard.scala:14:21
  reg       buffer_4;	// src/main/scala/exp7/PS2Keyboard.scala:14:21
  reg       buffer_5;	// src/main/scala/exp7/PS2Keyboard.scala:14:21
  reg       buffer_6;	// src/main/scala/exp7/PS2Keyboard.scala:14:21
  reg       buffer_7;	// src/main/scala/exp7/PS2Keyboard.scala:14:21
  reg       buffer_8;	// src/main/scala/exp7/PS2Keyboard.scala:14:21
  reg       buffer_9;	// src/main/scala/exp7/PS2Keyboard.scala:14:21
  reg [3:0] count;	// src/main/scala/exp7/PS2Keyboard.scala:16:24
  always @(posedge clock) begin	// src/main/scala/exp7/PS2Keyboard.scala:6:7
    automatic logic sampling;	// src/main/scala/exp7/PS2Keyboard.scala:19:33
    automatic logic _GEN;	// src/main/scala/exp7/PS2Keyboard.scala:22:20
    sampling = ps2_clk_sync[2] & ~(ps2_clk_sync[1]);	// src/main/scala/exp7/PS2Keyboard.scala:13:26, :19:{29,33,35,48}
    _GEN = count < 4'hA;	// src/main/scala/exp7/PS2Keyboard.scala:16:24, :22:20
    ps2_clk_sync <= {ps2_clk_sync[1:0], io_ps2_clk};	// src/main/scala/exp7/PS2Keyboard.scala:13:26, :18:{24,37}
    if (sampling & _GEN & count == 4'h0)	// src/main/scala/exp7/PS2Keyboard.scala:14:21, :16:24, :19:33, :21:20, :22:{20,28}, :23:27
      buffer_0 <= io_ps2_data;	// src/main/scala/exp7/PS2Keyboard.scala:14:21
    if (sampling & _GEN & count == 4'h1)	// src/main/scala/exp7/PS2Keyboard.scala:14:21, :16:24, :19:33, :21:20, :22:{20,28}, :23:27
      buffer_1 <= io_ps2_data;	// src/main/scala/exp7/PS2Keyboard.scala:14:21
    if (sampling & _GEN & count == 4'h2)	// src/main/scala/exp7/PS2Keyboard.scala:14:21, :16:24, :19:33, :21:20, :22:{20,28}, :23:27
      buffer_2 <= io_ps2_data;	// src/main/scala/exp7/PS2Keyboard.scala:14:21
    if (sampling & _GEN & count == 4'h3)	// src/main/scala/exp7/PS2Keyboard.scala:14:21, :16:24, :19:33, :21:20, :22:{20,28}, :23:27
      buffer_3 <= io_ps2_data;	// src/main/scala/exp7/PS2Keyboard.scala:14:21
    if (sampling & _GEN & count == 4'h4)	// src/main/scala/exp7/PS2Keyboard.scala:14:21, :16:24, :19:33, :21:20, :22:{20,28}, :23:27
      buffer_4 <= io_ps2_data;	// src/main/scala/exp7/PS2Keyboard.scala:14:21
    if (sampling & _GEN & count == 4'h5)	// src/main/scala/exp7/PS2Keyboard.scala:14:21, :16:24, :19:33, :21:20, :22:{20,28}, :23:27
      buffer_5 <= io_ps2_data;	// src/main/scala/exp7/PS2Keyboard.scala:14:21
    if (sampling & _GEN & count == 4'h6)	// src/main/scala/exp7/PS2Keyboard.scala:14:21, :16:24, :19:33, :21:20, :22:{20,28}, :23:27
      buffer_6 <= io_ps2_data;	// src/main/scala/exp7/PS2Keyboard.scala:14:21
    if (sampling & _GEN & count == 4'h7)	// src/main/scala/exp7/PS2Keyboard.scala:14:21, :16:24, :19:33, :21:20, :22:{20,28}, :23:27
      buffer_7 <= io_ps2_data;	// src/main/scala/exp7/PS2Keyboard.scala:14:21
    if (sampling & _GEN & count == 4'h8)	// src/main/scala/exp7/PS2Keyboard.scala:14:21, :16:24, :19:33, :21:20, :22:{20,28}, :23:27
      buffer_8 <= io_ps2_data;	// src/main/scala/exp7/PS2Keyboard.scala:14:21
    if (sampling & _GEN & count == 4'h9)	// src/main/scala/exp7/PS2Keyboard.scala:14:21, :16:24, :19:33, :21:20, :22:{20,28}, :23:27
      buffer_9 <= io_ps2_data;	// src/main/scala/exp7/PS2Keyboard.scala:14:21
    if (reset)	// src/main/scala/exp7/PS2Keyboard.scala:6:7
      count <= 4'h0;	// src/main/scala/exp7/PS2Keyboard.scala:16:24
    else if (sampling) begin	// src/main/scala/exp7/PS2Keyboard.scala:19:33
      if (_GEN)	// src/main/scala/exp7/PS2Keyboard.scala:22:20
        count <= count + 4'h1;	// src/main/scala/exp7/PS2Keyboard.scala:16:24, :23:27, :24:28
      else if (count == 4'hA)	// src/main/scala/exp7/PS2Keyboard.scala:16:24, :22:20, :25:26
        count <= 4'h0;	// src/main/scala/exp7/PS2Keyboard.scala:16:24
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// src/main/scala/exp7/PS2Keyboard.scala:6:7
    `ifdef FIRRTL_BEFORE_INITIAL	// src/main/scala/exp7/PS2Keyboard.scala:6:7
      `FIRRTL_BEFORE_INITIAL	// src/main/scala/exp7/PS2Keyboard.scala:6:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// src/main/scala/exp7/PS2Keyboard.scala:6:7
      automatic logic [31:0] _RANDOM[0:0];	// src/main/scala/exp7/PS2Keyboard.scala:6:7
      `ifdef INIT_RANDOM_PROLOG_	// src/main/scala/exp7/PS2Keyboard.scala:6:7
        `INIT_RANDOM_PROLOG_	// src/main/scala/exp7/PS2Keyboard.scala:6:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// src/main/scala/exp7/PS2Keyboard.scala:6:7
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// src/main/scala/exp7/PS2Keyboard.scala:6:7
        ps2_clk_sync = _RANDOM[/*Zero width*/ 1'b0][2:0];	// src/main/scala/exp7/PS2Keyboard.scala:6:7, :13:26
        buffer_0 = _RANDOM[/*Zero width*/ 1'b0][3];	// src/main/scala/exp7/PS2Keyboard.scala:6:7, :13:26, :14:21
        buffer_1 = _RANDOM[/*Zero width*/ 1'b0][4];	// src/main/scala/exp7/PS2Keyboard.scala:6:7, :13:26, :14:21
        buffer_2 = _RANDOM[/*Zero width*/ 1'b0][5];	// src/main/scala/exp7/PS2Keyboard.scala:6:7, :13:26, :14:21
        buffer_3 = _RANDOM[/*Zero width*/ 1'b0][6];	// src/main/scala/exp7/PS2Keyboard.scala:6:7, :13:26, :14:21
        buffer_4 = _RANDOM[/*Zero width*/ 1'b0][7];	// src/main/scala/exp7/PS2Keyboard.scala:6:7, :13:26, :14:21
        buffer_5 = _RANDOM[/*Zero width*/ 1'b0][8];	// src/main/scala/exp7/PS2Keyboard.scala:6:7, :13:26, :14:21
        buffer_6 = _RANDOM[/*Zero width*/ 1'b0][9];	// src/main/scala/exp7/PS2Keyboard.scala:6:7, :13:26, :14:21
        buffer_7 = _RANDOM[/*Zero width*/ 1'b0][10];	// src/main/scala/exp7/PS2Keyboard.scala:6:7, :13:26, :14:21
        buffer_8 = _RANDOM[/*Zero width*/ 1'b0][11];	// src/main/scala/exp7/PS2Keyboard.scala:6:7, :13:26, :14:21
        buffer_9 = _RANDOM[/*Zero width*/ 1'b0][12];	// src/main/scala/exp7/PS2Keyboard.scala:6:7, :13:26, :14:21
        count = _RANDOM[/*Zero width*/ 1'b0][16:13];	// src/main/scala/exp7/PS2Keyboard.scala:6:7, :13:26, :16:24
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// src/main/scala/exp7/PS2Keyboard.scala:6:7
      `FIRRTL_AFTER_INITIAL	// src/main/scala/exp7/PS2Keyboard.scala:6:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_out_valid = count == 4'hA;	// src/main/scala/exp7/PS2Keyboard.scala:6:7, :16:24, :22:20, :30:27
  assign io_out_bits =
    {buffer_8, buffer_7, buffer_6, buffer_5, buffer_4, buffer_3, buffer_2, buffer_1};	// src/main/scala/exp7/PS2Keyboard.scala:6:7, :14:21, :31:33
endmodule

