// Generated by CIRCT firtool-1.62.0
module Bcd7seg(	// src/main/scala/exp2/Bcd7seg.scala:6:7
  input        clock,	// src/main/scala/exp2/Bcd7seg.scala:6:7
               reset,	// src/main/scala/exp2/Bcd7seg.scala:6:7
  input  [3:0] io_input,	// src/main/scala/exp2/Bcd7seg.scala:7:16
  output [6:0] io_output	// src/main/scala/exp2/Bcd7seg.scala:7:16
);

  wire [15:0][6:0] _GEN =
    '{7'h0,
      7'h0,
      7'h0,
      7'h0,
      7'h0,
      7'h0,
      7'h0,
      7'h00,
      7'h78,
      7'h02,
      7'h12,
      7'h19,
      7'h30,
      7'h24,
      7'h79,
      7'h40};	// src/main/scala/exp2/Bcd7seg.scala:12:26, :14:22, :16:17, :19:17, :22:17, :25:17, :28:17, :31:17, :34:17, :37:17, :40:17, :43:17
  assign io_output = _GEN[io_input];	// src/main/scala/exp2/Bcd7seg.scala:6:7, :12:26, :14:22, :16:17, :19:17, :22:17, :25:17, :28:17, :31:17, :34:17, :37:17, :40:17, :43:17
endmodule

