// Generated by CIRCT firtool-1.62.0
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

module LinearFeedbackShiftReg(	// src/main/scala/exp6/LinearFeedbackShiftReg.scala:6:7
  input        clock,	// src/main/scala/exp6/LinearFeedbackShiftReg.scala:6:7
               reset,	// src/main/scala/exp6/LinearFeedbackShiftReg.scala:6:7
  output [7:0] io_dout	// src/main/scala/exp6/LinearFeedbackShiftReg.scala:7:16
);

  reg [7:0] shiftReg;	// src/main/scala/exp6/LinearFeedbackShiftReg.scala:11:27
  always @(posedge clock) begin	// src/main/scala/exp6/LinearFeedbackShiftReg.scala:6:7
    if (reset)	// src/main/scala/exp6/LinearFeedbackShiftReg.scala:6:7
      shiftReg <= 8'h1;	// src/main/scala/exp6/LinearFeedbackShiftReg.scala:11:27, :15:28, :18:18, :20:18
    else if (|shiftReg)	// src/main/scala/exp6/LinearFeedbackShiftReg.scala:11:27, :15:19
      shiftReg <=
        {(|shiftReg) & (shiftReg[4] ^ shiftReg[3] ^ shiftReg[2] ^ shiftReg[0]),
         shiftReg[7:1]};	// src/main/scala/exp6/LinearFeedbackShiftReg.scala:11:27, :13:33, :15:{19,28}, :16:{20,31,45,59,63,73}, :18:{24,45}
    else	// src/main/scala/exp6/LinearFeedbackShiftReg.scala:15:19
      shiftReg <= 8'h1;	// src/main/scala/exp6/LinearFeedbackShiftReg.scala:11:27, :15:28, :18:18, :20:18
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// src/main/scala/exp6/LinearFeedbackShiftReg.scala:6:7
    `ifdef FIRRTL_BEFORE_INITIAL	// src/main/scala/exp6/LinearFeedbackShiftReg.scala:6:7
      `FIRRTL_BEFORE_INITIAL	// src/main/scala/exp6/LinearFeedbackShiftReg.scala:6:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// src/main/scala/exp6/LinearFeedbackShiftReg.scala:6:7
      automatic logic [31:0] _RANDOM[0:0];	// src/main/scala/exp6/LinearFeedbackShiftReg.scala:6:7
      `ifdef INIT_RANDOM_PROLOG_	// src/main/scala/exp6/LinearFeedbackShiftReg.scala:6:7
        `INIT_RANDOM_PROLOG_	// src/main/scala/exp6/LinearFeedbackShiftReg.scala:6:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// src/main/scala/exp6/LinearFeedbackShiftReg.scala:6:7
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// src/main/scala/exp6/LinearFeedbackShiftReg.scala:6:7
        shiftReg = _RANDOM[/*Zero width*/ 1'b0][7:0];	// src/main/scala/exp6/LinearFeedbackShiftReg.scala:6:7, :11:27
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// src/main/scala/exp6/LinearFeedbackShiftReg.scala:6:7
      `FIRRTL_AFTER_INITIAL	// src/main/scala/exp6/LinearFeedbackShiftReg.scala:6:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_dout = shiftReg;	// src/main/scala/exp6/LinearFeedbackShiftReg.scala:6:7, :11:27
endmodule

module Encoder(	// src/main/scala/exp6/Bin2HexSeg.scala:7:7
  input  [3:0] io_hex,	// src/main/scala/exp6/Bin2HexSeg.scala:8:16
  output [6:0] io_seg	// src/main/scala/exp6/Bin2HexSeg.scala:8:16
);

  wire [15:0][6:0] _GEN =
    '{7'hE,
      7'h6,
      7'h21,
      7'h46,
      7'h3,
      7'h8,
      7'h10,
      7'h0,
      7'h78,
      7'h2,
      7'h12,
      7'h19,
      7'h30,
      7'h24,
      7'h79,
      7'h40};	// src/main/scala/exp6/Bin2HexSeg.scala:13:37
  assign io_seg = _GEN[io_hex];	// src/main/scala/exp6/Bin2HexSeg.scala:7:7, :13:37
endmodule

module HexSeg(	// src/main/scala/exp6/Bin2HexSeg.scala:33:7
  input  [7:0] io_binary,	// src/main/scala/exp6/Bin2HexSeg.scala:34:16
  output [6:0] io_seg1,	// src/main/scala/exp6/Bin2HexSeg.scala:34:16
               io_seg2	// src/main/scala/exp6/Bin2HexSeg.scala:34:16
);

  Encoder enc1 (	// src/main/scala/exp6/Bin2HexSeg.scala:40:22
    .io_hex (io_binary[3:0]),	// src/main/scala/exp6/Bin2HexSeg.scala:43:29
    .io_seg (io_seg1)
  );
  Encoder enc2 (	// src/main/scala/exp6/Bin2HexSeg.scala:41:22
    .io_hex (io_binary[7:4]),	// src/main/scala/exp6/Bin2HexSeg.scala:44:29
    .io_seg (io_seg2)
  );
endmodule

module LFSRTop(	// src/main/scala/exp6/LFSRTop.scala:6:7
  input        clock,	// src/main/scala/exp6/LFSRTop.scala:6:7
               reset,	// src/main/scala/exp6/LFSRTop.scala:6:7
  output [6:0] io_seg1,	// src/main/scala/exp6/LFSRTop.scala:7:16
               io_seg2	// src/main/scala/exp6/LFSRTop.scala:7:16
);

  wire [7:0] _lsfr_io_dout;	// src/main/scala/exp6/LFSRTop.scala:13:22
  LinearFeedbackShiftReg lsfr (	// src/main/scala/exp6/LFSRTop.scala:13:22
    .clock   (clock),
    .reset   (reset),
    .io_dout (_lsfr_io_dout)
  );
  HexSeg bin2hexseg (	// src/main/scala/exp6/LFSRTop.scala:14:28
    .io_binary (_lsfr_io_dout),	// src/main/scala/exp6/LFSRTop.scala:13:22
    .io_seg1   (io_seg1),
    .io_seg2   (io_seg2)
  );
endmodule

