// Generated by CIRCT firtool-1.62.0
module MuxKeyInternal(	// src/main/scala/exp1/MuxFramework.scala:11:7
  input  [1:0] io_key,	// src/main/scala/exp1/MuxFramework.scala:12:16
               io_lut_0_data,	// src/main/scala/exp1/MuxFramework.scala:12:16
               io_lut_1_data,	// src/main/scala/exp1/MuxFramework.scala:12:16
               io_lut_2_data,	// src/main/scala/exp1/MuxFramework.scala:12:16
               io_lut_3_data,	// src/main/scala/exp1/MuxFramework.scala:12:16
  output [1:0] io_out	// src/main/scala/exp1/MuxFramework.scala:12:16
);

  wire [3:0][1:0] _GEN =
    {{io_lut_3_data}, {io_lut_2_data}, {io_lut_1_data}, {io_lut_0_data}};	// src/main/scala/exp1/MuxFramework.scala:22:12, :26:{21,40}, :27:20
  assign io_out =
    (&io_key) | io_key == 2'h2 | io_key == 2'h1 | io_key == 2'h0 ? _GEN[io_key] : 2'h0;	// src/main/scala/exp1/MuxFramework.scala:11:7, :12:16, :22:12, :26:{21,40}, :27:20, :28:17, :32:18
endmodule

module MuxKey(	// src/main/scala/exp1/MuxFramework.scala:35:7
  input  [1:0] io_key,	// src/main/scala/exp1/MuxFramework.scala:36:16
               io_lut_0_data,	// src/main/scala/exp1/MuxFramework.scala:36:16
               io_lut_1_data,	// src/main/scala/exp1/MuxFramework.scala:36:16
               io_lut_2_data,	// src/main/scala/exp1/MuxFramework.scala:36:16
               io_lut_3_data,	// src/main/scala/exp1/MuxFramework.scala:36:16
  output [1:0] io_out	// src/main/scala/exp1/MuxFramework.scala:36:16
);

  MuxKeyInternal internal (	// src/main/scala/exp1/MuxFramework.scala:42:26
    .io_key        (io_key),
    .io_lut_0_data (io_lut_0_data),
    .io_lut_1_data (io_lut_1_data),
    .io_lut_2_data (io_lut_2_data),
    .io_lut_3_data (io_lut_3_data),
    .io_out        (io_out)
  );
endmodule

module Mux41_2bit(	// src/main/scala/exp1/MuxFramework.scala:90:7
  input        clock,	// src/main/scala/exp1/MuxFramework.scala:90:7
               reset,	// src/main/scala/exp1/MuxFramework.scala:90:7
  input  [1:0] io_x0,	// src/main/scala/exp1/MuxFramework.scala:91:16
               io_x1,	// src/main/scala/exp1/MuxFramework.scala:91:16
               io_x2,	// src/main/scala/exp1/MuxFramework.scala:91:16
               io_x3,	// src/main/scala/exp1/MuxFramework.scala:91:16
               io_y,	// src/main/scala/exp1/MuxFramework.scala:91:16
  output [1:0] io_f	// src/main/scala/exp1/MuxFramework.scala:91:16
);

  MuxKey muxkey (	// src/main/scala/exp1/MuxFramework.scala:100:24
    .io_key        (io_y),
    .io_lut_0_data (io_x0),
    .io_lut_1_data (io_x1),
    .io_lut_2_data (io_x2),
    .io_lut_3_data (io_x3),
    .io_out        (io_f)
  );
endmodule

