// Generated by CIRCT firtool-1.62.0
module BucketShiftReg(	// src/main/scala/exp6/BucketShiftReg.scala:6:7
  input        clock,	// src/main/scala/exp6/BucketShiftReg.scala:6:7
               reset,	// src/main/scala/exp6/BucketShiftReg.scala:6:7
  input  [7:0] io_din,	// src/main/scala/exp6/BucketShiftReg.scala:7:16
  input  [2:0] io_shamt,	// src/main/scala/exp6/BucketShiftReg.scala:7:16
  input        io_LorR,	// src/main/scala/exp6/BucketShiftReg.scala:7:16
               io_AorL,	// src/main/scala/exp6/BucketShiftReg.scala:7:16
  output [7:0] io_dout	// src/main/scala/exp6/BucketShiftReg.scala:7:16
);

  wire       AorL = io_AorL & io_din[7];	// src/main/scala/exp6/BucketShiftReg.scala:16:{16,32}
  wire [1:0] layer1Cnt = {io_LorR, io_shamt[0]};	// src/main/scala/exp6/BucketShiftReg.scala:23:{24,49}
  wire [1:0] layer2Cnt = {io_LorR, io_shamt[1]};	// src/main/scala/exp6/BucketShiftReg.scala:24:{24,49}
  wire [1:0] layer3Cnt = {io_LorR, io_shamt[2]};	// src/main/scala/exp6/BucketShiftReg.scala:25:{24,49}
  wire       _layer1_7_T_5 = layer1Cnt == 2'h2;	// src/main/scala/exp6/BucketShiftReg.scala:23:24, :28:43
  wire       _GEN = layer1Cnt != 2'h1;	// src/main/scala/exp6/BucketShiftReg.scala:23:24, :28:43
  wire       _GEN_0 = _layer1_7_T_5 | _GEN;	// src/main/scala/exp6/BucketShiftReg.scala:28:43
  wire       layer1_0 = ~(&layer1Cnt) & (_GEN_0 ? io_din[0] : io_din[1]);	// src/main/scala/exp6/BucketShiftReg.scala:23:24, :28:43, :29:22, :30:22
  wire       layer1_1 = (&layer1Cnt) ? io_din[0] : _GEN_0 ? io_din[1] : io_din[2];	// src/main/scala/exp6/BucketShiftReg.scala:23:24, :28:43, :29:22, :30:22, :36:47, :38:26
  wire       layer1_2 = (&layer1Cnt) ? io_din[1] : _GEN_0 ? io_din[2] : io_din[3];	// src/main/scala/exp6/BucketShiftReg.scala:23:24, :28:43, :30:22, :36:47, :38:26
  wire       layer1_3 = (&layer1Cnt) ? io_din[2] : _GEN_0 ? io_din[3] : io_din[4];	// src/main/scala/exp6/BucketShiftReg.scala:23:24, :28:43, :36:47, :38:26
  wire       layer1_4 = (&layer1Cnt) ? io_din[3] : _GEN_0 ? io_din[4] : io_din[5];	// src/main/scala/exp6/BucketShiftReg.scala:23:24, :28:43, :36:47, :38:26
  wire       layer1_5 = (&layer1Cnt) ? io_din[4] : _GEN_0 ? io_din[5] : io_din[6];	// src/main/scala/exp6/BucketShiftReg.scala:23:24, :28:43, :36:47, :38:26
  wire       layer1_6 = (&layer1Cnt) ? io_din[5] : _GEN_0 ? io_din[6] : io_din[7];	// src/main/scala/exp6/BucketShiftReg.scala:16:32, :23:24, :28:43, :36:47, :38:26
  wire       layer1_7 =
    (&layer1Cnt) ? io_din[6] : (_layer1_7_T_5 | _GEN | io_AorL) & io_din[7];	// src/main/scala/exp6/BucketShiftReg.scala:16:32, :23:24, :28:43, :38:26, :44:43
  wire       _GEN_1 = layer2Cnt == 2'h2 | layer2Cnt != 2'h1;	// src/main/scala/exp6/BucketShiftReg.scala:24:24, :28:43, :54:47
  wire       layer2_0 = ~(&layer2Cnt) & (_GEN_1 ? layer1_0 : layer1_2);	// src/main/scala/exp6/BucketShiftReg.scala:24:24, :28:43, :36:47, :54:47
  wire       layer2_1 = ~(&layer2Cnt) & (_GEN_1 ? layer1_1 : layer1_3);	// src/main/scala/exp6/BucketShiftReg.scala:24:24, :36:47, :54:47
  wire       layer2_2 = (&layer2Cnt) ? layer1_0 : _GEN_1 ? layer1_2 : layer1_4;	// src/main/scala/exp6/BucketShiftReg.scala:24:24, :28:43, :36:47, :54:47, :63:47
  wire       layer2_3 = (&layer2Cnt) ? layer1_1 : _GEN_1 ? layer1_3 : layer1_5;	// src/main/scala/exp6/BucketShiftReg.scala:24:24, :36:47, :54:47, :63:47
  wire       layer2_4 = (&layer2Cnt) ? layer1_2 : _GEN_1 ? layer1_4 : layer1_6;	// src/main/scala/exp6/BucketShiftReg.scala:24:24, :36:47, :54:47, :63:47
  wire       layer2_5 = (&layer2Cnt) ? layer1_3 : _GEN_1 ? layer1_5 : layer1_7;	// src/main/scala/exp6/BucketShiftReg.scala:24:24, :36:47, :44:43, :54:47, :63:47
  wire       layer2_6 = (&layer2Cnt) ? layer1_4 : _GEN_1 ? layer1_6 : AorL;	// src/main/scala/exp6/BucketShiftReg.scala:16:16, :24:24, :36:47, :54:47, :72:47
  wire       layer2_7 = (&layer2Cnt) ? layer1_5 : _GEN_1 ? layer1_7 : AorL;	// src/main/scala/exp6/BucketShiftReg.scala:16:16, :24:24, :36:47, :44:43, :54:47, :72:47
  wire       _GEN_2 = layer3Cnt == 2'h2 | layer3Cnt != 2'h1;	// src/main/scala/exp6/BucketShiftReg.scala:25:24, :28:43, :83:47
  assign io_dout =
    {(&layer3Cnt) ? layer2_3 : _GEN_2 ? layer2_7 : AorL,
     (&layer3Cnt) ? layer2_2 : _GEN_2 ? layer2_6 : AorL,
     (&layer3Cnt) ? layer2_1 : _GEN_2 ? layer2_5 : AorL,
     (&layer3Cnt) ? layer2_0 : _GEN_2 ? layer2_4 : AorL,
     ~(&layer3Cnt) & (_GEN_2 ? layer2_3 : layer2_7),
     ~(&layer3Cnt) & (_GEN_2 ? layer2_2 : layer2_6),
     ~(&layer3Cnt) & (_GEN_2 ? layer2_1 : layer2_5),
     ~(&layer3Cnt) & (_GEN_2 ? layer2_0 : layer2_4)};	// src/main/scala/exp6/BucketShiftReg.scala:6:7, :16:16, :25:24, :54:47, :63:47, :72:47, :83:47, :91:47, :100:23
endmodule

