// Generated by CIRCT firtool-1.62.0
module Encode83p(	// src/main/scala/exp2/Encode83p.scala:6:7
  input  [7:0] io_input,	// src/main/scala/exp2/Encode83p.scala:7:16
  input        io_en,	// src/main/scala/exp2/Encode83p.scala:7:16
  output [2:0] io_out,	// src/main/scala/exp2/Encode83p.scala:7:16
  output       io_indicate	// src/main/scala/exp2/Encode83p.scala:7:16
);

  assign io_out =
    io_en
      ? (io_input[7]
           ? 3'h7
           : io_input[6]
               ? 3'h6
               : io_input[5]
                   ? 3'h5
                   : io_input[4]
                       ? 3'h4
                       : io_input[3] ? 3'h3 : io_input[2] ? 3'h2 : {2'h0, io_input[1]})
      : 3'h0;	// src/main/scala/exp2/Encode83p.scala:6:7, :14:26, :16:17, :18:{26,31}, :19:21, :23:13
  assign io_indicate = io_input == 8'h0;	// src/main/scala/exp2/Encode83p.scala:6:7, :26:30
endmodule

module Bcd7seg(	// src/main/scala/exp2/Bcd7seg.scala:7:7
  input  [3:0] io_input,	// src/main/scala/exp2/Bcd7seg.scala:8:16
  output [6:0] io_output	// src/main/scala/exp2/Bcd7seg.scala:8:16
);

  assign io_output =
    io_input == 4'h0
      ? 7'h40
      : io_input == 4'h1
          ? 7'h79
          : io_input == 4'h2
              ? 7'h24
              : io_input == 4'h3
                  ? 7'h30
                  : io_input == 4'h4
                      ? 7'h19
                      : io_input == 4'h5
                          ? 7'h12
                          : io_input == 4'h6
                              ? 7'h2
                              : io_input == 4'h7
                                  ? 7'h78
                                  : io_input == 4'h8
                                      ? 7'h0
                                      : {2'h0, io_input == 4'h9, 4'h0};	// src/main/scala/exp2/Bcd7seg.scala:7:7, :13:26, :15:22, :17:17, :20:17, :23:17, :26:17, :29:17, :32:17, :35:17, :38:17, :41:17, :44:17
endmodule

module Segtop(	// src/main/scala/exp2/Encode83p.scala:34:7
  input        clock,	// src/main/scala/exp2/Encode83p.scala:34:7
               reset,	// src/main/scala/exp2/Encode83p.scala:34:7
  input  [7:0] io_input,	// src/main/scala/exp2/Encode83p.scala:35:16
  input        io_en,	// src/main/scala/exp2/Encode83p.scala:35:16
  output [6:0] io_seg,	// src/main/scala/exp2/Encode83p.scala:35:16
  output       io_indicate	// src/main/scala/exp2/Encode83p.scala:35:16
);

  wire [2:0] _encode83p_io_out;	// src/main/scala/exp2/Encode83p.scala:42:27
  Encode83p encode83p (	// src/main/scala/exp2/Encode83p.scala:42:27
    .io_input    (io_input),
    .io_en       (io_en),
    .io_out      (_encode83p_io_out),
    .io_indicate (io_indicate)
  );
  Bcd7seg bcd7seg (	// src/main/scala/exp2/Encode83p.scala:43:25
    .io_input  ({1'h0, _encode83p_io_out}),	// src/main/scala/exp2/Encode83p.scala:42:27, :48:28
    .io_output (io_seg)
  );
endmodule

