// Generated by CIRCT firtool-1.62.0
module FA(	// src/main/scala/exp3/FA.scala:6:7
  input  io_a,	// src/main/scala/exp3/FA.scala:7:16
         io_b,	// src/main/scala/exp3/FA.scala:7:16
         io_cin,	// src/main/scala/exp3/FA.scala:7:16
  output io_s,	// src/main/scala/exp3/FA.scala:7:16
         io_cout	// src/main/scala/exp3/FA.scala:7:16
);

  assign io_s = io_a ^ io_b ^ io_cin;	// src/main/scala/exp3/FA.scala:6:7, :15:25
  assign io_cout = (io_a & io_b) + (io_a & io_cin) + (io_b & io_cin);	// src/main/scala/exp3/FA.scala:6:7, :16:{22,38,48,56}
endmodule

module SerialAdder(	// src/main/scala/exp3/SerialAdder.scala:6:7
  input  [3:0] io_a,	// src/main/scala/exp3/SerialAdder.scala:7:16
               io_b,	// src/main/scala/exp3/SerialAdder.scala:7:16
  output [3:0] io_output,	// src/main/scala/exp3/SerialAdder.scala:7:16
  output       io_cout	// src/main/scala/exp3/SerialAdder.scala:7:16
);

  wire _FA_3_io_s;	// src/main/scala/exp3/SerialAdder.scala:14:48
  wire _FA_2_io_s;	// src/main/scala/exp3/SerialAdder.scala:14:48
  wire _FA_2_io_cout;	// src/main/scala/exp3/SerialAdder.scala:14:48
  wire _FA_1_io_s;	// src/main/scala/exp3/SerialAdder.scala:14:48
  wire _FA_1_io_cout;	// src/main/scala/exp3/SerialAdder.scala:14:48
  wire _FA_io_s;	// src/main/scala/exp3/SerialAdder.scala:14:48
  wire _FA_io_cout;	// src/main/scala/exp3/SerialAdder.scala:14:48
  FA FA (	// src/main/scala/exp3/SerialAdder.scala:14:48
    .io_a    (io_a[0]),	// src/main/scala/exp3/SerialAdder.scala:17:28
    .io_b    (io_b[0]),	// src/main/scala/exp3/SerialAdder.scala:18:28
    .io_cin  (1'h0),	// src/main/scala/exp3/SerialAdder.scala:20:19
    .io_s    (_FA_io_s),
    .io_cout (_FA_io_cout)
  );
  FA FA_1 (	// src/main/scala/exp3/SerialAdder.scala:14:48
    .io_a    (io_a[1]),	// src/main/scala/exp3/SerialAdder.scala:17:28
    .io_b    (io_b[1]),	// src/main/scala/exp3/SerialAdder.scala:18:28
    .io_cin  (_FA_io_cout),	// src/main/scala/exp3/SerialAdder.scala:14:48
    .io_s    (_FA_1_io_s),
    .io_cout (_FA_1_io_cout)
  );
  FA FA_2 (	// src/main/scala/exp3/SerialAdder.scala:14:48
    .io_a    (io_a[2]),	// src/main/scala/exp3/SerialAdder.scala:17:28
    .io_b    (io_b[2]),	// src/main/scala/exp3/SerialAdder.scala:18:28
    .io_cin  (_FA_1_io_cout),	// src/main/scala/exp3/SerialAdder.scala:14:48
    .io_s    (_FA_2_io_s),
    .io_cout (_FA_2_io_cout)
  );
  FA FA_3 (	// src/main/scala/exp3/SerialAdder.scala:14:48
    .io_a    (io_a[3]),	// src/main/scala/exp3/SerialAdder.scala:21:30
    .io_b    (io_b[3]),	// src/main/scala/exp3/SerialAdder.scala:22:30
    .io_cin  (_FA_2_io_cout),	// src/main/scala/exp3/SerialAdder.scala:14:48
    .io_s    (_FA_3_io_s),
    .io_cout (io_cout)
  );
  assign io_output = {_FA_3_io_s, _FA_2_io_s, _FA_1_io_s, _FA_io_s};	// src/main/scala/exp3/SerialAdder.scala:6:7, :14:48, :30:22
endmodule

module Adder(	// src/main/scala/exp3/Adder.scala:6:7
  input        clock,	// src/main/scala/exp3/Adder.scala:6:7
               reset,	// src/main/scala/exp3/Adder.scala:6:7
               io_sub,	// src/main/scala/exp3/Adder.scala:7:16
  input  [3:0] io_A,	// src/main/scala/exp3/Adder.scala:7:16
               io_B,	// src/main/scala/exp3/Adder.scala:7:16
  output       io_carry,	// src/main/scala/exp3/Adder.scala:7:16
               io_zero,	// src/main/scala/exp3/Adder.scala:7:16
               io_overflow,	// src/main/scala/exp3/Adder.scala:7:16
  output [3:0] io_result	// src/main/scala/exp3/Adder.scala:7:16
);

  wire [3:0] _serialadder_io_output;	// src/main/scala/exp3/Adder.scala:17:29
  SerialAdder serialadder (	// src/main/scala/exp3/Adder.scala:17:29
    .io_a      (io_A),
    .io_b      (io_sub ? ~io_B + 4'h1 : io_B),	// src/main/scala/exp3/Adder.scala:23:{19,29,35}
    .io_output (_serialadder_io_output),
    .io_cout   (io_carry)
  );
  assign io_zero = _serialadder_io_output == 4'h0;	// src/main/scala/exp3/Adder.scala:6:7, :17:29, :30:24
  assign io_overflow = io_A[3] == io_B[3] & _serialadder_io_output[3] != io_A[3];	// src/main/scala/exp3/Adder.scala:6:7, :17:29, :31:{25,29,37,42,52,56}
  assign io_result = _serialadder_io_output;	// src/main/scala/exp3/Adder.scala:6:7, :17:29
endmodule

