// Generated by CIRCT firtool-1.62.0
module FA(	// src/main/scala/exp3/FA.scala:6:7
  input  clock,	// src/main/scala/exp3/FA.scala:6:7
         reset,	// src/main/scala/exp3/FA.scala:6:7
         io_a,	// src/main/scala/exp3/FA.scala:7:16
         io_b,	// src/main/scala/exp3/FA.scala:7:16
         io_cin,	// src/main/scala/exp3/FA.scala:7:16
  output io_s,	// src/main/scala/exp3/FA.scala:7:16
         io_cout	// src/main/scala/exp3/FA.scala:7:16
);

  assign io_s = io_a ^ io_b ^ io_cin;	// src/main/scala/exp3/FA.scala:6:7, :15:25
  assign io_cout = (io_a & io_b) + (io_a & io_cin) + (io_b & io_cin);	// src/main/scala/exp3/FA.scala:6:7, :16:{22,38,48,56}
endmodule

