// Generated by CIRCT firtool-1.62.0
module MuxKeyInternal(	// src/main/scala/exp1/MuxFramework.scala:11:7
  input        io_key,	// src/main/scala/exp1/MuxFramework.scala:12:16
  input  [3:0] io_lut_0_data,	// src/main/scala/exp1/MuxFramework.scala:12:16
               io_lut_1_data,	// src/main/scala/exp1/MuxFramework.scala:12:16
  output [3:0] io_out	// src/main/scala/exp1/MuxFramework.scala:12:16
);

  assign io_out = io_key ? io_lut_1_data : io_lut_0_data;	// src/main/scala/exp1/MuxFramework.scala:11:7, :26:40, :27:20
endmodule

module MuxKey(	// src/main/scala/exp1/MuxFramework.scala:35:7
  input        io_key,	// src/main/scala/exp1/MuxFramework.scala:36:16
  input  [3:0] io_lut_0_data,	// src/main/scala/exp1/MuxFramework.scala:36:16
               io_lut_1_data,	// src/main/scala/exp1/MuxFramework.scala:36:16
  output [3:0] io_out	// src/main/scala/exp1/MuxFramework.scala:36:16
);

  MuxKeyInternal internal (	// src/main/scala/exp1/MuxFramework.scala:42:26
    .io_key        (io_key),
    .io_lut_0_data (io_lut_0_data),
    .io_lut_1_data (io_lut_1_data),
    .io_out        (io_out)
  );
endmodule

module Mux21(	// src/main/scala/exp1/MuxFramework.scala:64:7
  input        clock,	// src/main/scala/exp1/MuxFramework.scala:64:7
               reset,	// src/main/scala/exp1/MuxFramework.scala:64:7
  input  [3:0] io_data1,	// src/main/scala/exp1/MuxFramework.scala:65:16
               io_data2,	// src/main/scala/exp1/MuxFramework.scala:65:16
  input        io_sel,	// src/main/scala/exp1/MuxFramework.scala:65:16
  output [3:0] io_out	// src/main/scala/exp1/MuxFramework.scala:65:16
);

  MuxKey muxkey (	// src/main/scala/exp1/MuxFramework.scala:71:24
    .io_key        (io_sel),
    .io_lut_0_data (io_data1),
    .io_lut_1_data (io_data2),
    .io_out        (io_out)
  );
endmodule

