// Generated by CIRCT firtool-1.62.0
module Encode83p(	// src/main/scala/exp2/Encode83p.scala:6:7
  input        clock,	// src/main/scala/exp2/Encode83p.scala:6:7
               reset,	// src/main/scala/exp2/Encode83p.scala:6:7
  input  [7:0] io_input,	// src/main/scala/exp2/Encode83p.scala:7:16
  input        io_en,	// src/main/scala/exp2/Encode83p.scala:7:16
  output [2:0] io_out,	// src/main/scala/exp2/Encode83p.scala:7:16
  output       io_indicate	// src/main/scala/exp2/Encode83p.scala:7:16
);

  assign io_out =
    io_en
      ? (io_input[7]
           ? 3'h7
           : io_input[6]
               ? 3'h6
               : io_input[5]
                   ? 3'h5
                   : io_input[4]
                       ? 3'h4
                       : io_input[3] ? 3'h3 : io_input[2] ? 3'h2 : {2'h0, io_input[1]})
      : 3'h0;	// src/main/scala/exp2/Encode83p.scala:6:7, :14:26, :16:17, :18:{26,31}, :19:21, :23:13
  assign io_indicate = io_input == 8'h0;	// src/main/scala/exp2/Encode83p.scala:6:7, :26:30
endmodule

