// Generated by CIRCT firtool-1.62.0
module DoubleControlSwitch(	// src/main/scala/exp0/DoubleControlSwitch.scala:5:7
  input  clock,	// src/main/scala/exp0/DoubleControlSwitch.scala:5:7
         reset,	// src/main/scala/exp0/DoubleControlSwitch.scala:5:7
         io_a,	// src/main/scala/exp0/DoubleControlSwitch.scala:6:16
         io_b,	// src/main/scala/exp0/DoubleControlSwitch.scala:6:16
  output io_f	// src/main/scala/exp0/DoubleControlSwitch.scala:6:16
);

  assign io_f = io_a ^ io_b;	// src/main/scala/exp0/DoubleControlSwitch.scala:5:7, :12:18
endmodule

